direct_transform:
    _target_: torchaudio.transforms.Spectrogram
    n_fft: 2048
    win_length: 2048
    hop_length: 441
    power: null
inverse_transform:
    _target_: torchaudio.transforms.InverseSpectrogram
    n_fft: 2048
    win_length: 2048
    hop_length: 441
multi_transform:
    _target_: torchaudio.transforms.Spectrogram
    hop_length: 147
    power: null

multi_n_fft: 2048
multi_win_length: [4096, 2048, 1024, 512, 256]
